#ifndef _SPRF_PLAYER_STATS_HPP_
#define _SPRF_PLAYER_STATS_HPP_

#define PLAYER_RADIUS (0.5)
#define PLAYER_HEIGHT (1.0)
#define PLAYER_FOOT_RADIUS (0.75)
#define PLAYER_FOOT_OFFSET (0.5)
#define PLAYER_MASS (1.0)

#endif // _SPRF_PLAYER_STATS_HPP_