image: atlassian/default-image:2

pipelines:
  default:
    - step:
        script:
          - apt-get update
          - apt-get -y install autoconf automake libtool
          - ./bootstrap
          - ./configure --enable-double-precision --enable-ou --enable-libccd
          - make
